apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: gitops
  POSTGRES_PASSWORD: gitops123
  POSTGRES_DB: gitops_insights
  DATABASE_URL: postgresql://gitops:gitops123@postgres:5432/gitops_insights?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
