apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-frontend
  template:
    metadata:
      labels:
        app: gitops-frontend
    spec:
      containers:
      - name: frontend
        image: ahmedashraf74/gitops-frontend:v19
        ports:
        - containerPort: 3000
